added view svg corners
xtravision-ai/xtravision-react-native pull request #33
Opened 2023-04-27 10:34 UTC by Jestin64

2023-04-27 17:56 UTC, mManishTrivedi requested changes
@Jestin64 :

- if possible then kindly break it into separate component so anyone can use it directly.
- Plz test it once with iPhone also. (@jinchuuriki91 and @riddhixtraining can help )
Rest things are okay
@Jestin64

2023-05-02 10:26 UTC, jinchuuriki91 approved these changes

2023-05-05 06:17 UTC, mManishTrivedi approved these changes

2023-05-05 06:18 UTC, mManishTrivedi commented
@riddhixtraining and @jinchuuriki91 
Kindly test this PR in IOS also

2023-05-10 06:32 UTC, merged